/*
 * ultrasonic.h
 *
 *  Created on: Mar 2, 2024
 *      Author: dell
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "std_types.h"

volatile uint8 g_edge_count;/*gloabal variable used in Ultrasonic_edgeProcessing() */
uint16 timer_value;

/*
 * Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver
*/
void Ultrasonic_init(void);


/*Description
➢ Send the Trigger pulse to the ultra-sonic */
void Ultrasonic_Trigger(void);

/*Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment */
uint16 Ultrasonic_readDistance(void);

/*
 * Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by the ultra-sonic sensor.*/
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
