/*
 * ultrasonic.c
 *
 *  Created on: Mar 2, 2024
 *      Author: dell
 */
#include "ultrasonic.h"
#include "icu_mine.h"
#include "gpio.h"
#include <avr/io.h> /* To use the SREG register */
#include <util/delay.h>/*for delay*/
#include <math.h>



/*
 * Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver
*/
void Ultrasonic_init(void)
{
	/* Enable Global Interrupt I-Bit */
		SREG |= (1<<7);

	GPIO_writePin(PORTB_ID,PIN5_ID, LOGIC_LOW);/*initial*/
				/**Initialize the ICU driver as required**/
	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Configurations = {F_CPU_CLOCK_8,RAISING};
	/*detect rising edge to detect when the ECHO pin is HIGG*/
	ICU_init(&ICU_Configurations);


				/**Setup the ICU call back function**/
	 ICU_setCallBack(Ultrasonic_edgeProcessing);

	 /**Setup the direction for the trigger pin as output pin through the GPIO driver**/
	 GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);/*TRIGGER PIN*/


}



/*
 * Description
➢ Send the Trigger pulse to the ultra-sonic */
void Ultrasonic_Trigger(void){

	/*trigger pin PB5 for 1us*/
	GPIO_writePin(PORTB_ID,PIN5_ID, LOGIC_HIGH);
	_delay_us(15);/*FOR 1us*/
	GPIO_writePin(PORTB_ID,PIN5_ID, LOGIC_LOW);
}

/*
 * Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment */
uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;
	/**Send the trigger pulse by using Ultrasonic_Trigger function**/
	Ultrasonic_Trigger();/*send trigger pulse*/

	/**Start the measurements by the ICU from this moment**/

	/**Sound velocity = 340.00 m/s = 34000 cm/s
	* The distance of Object (in cm) = (340000 x Time)/2 = 17000 x Time
	* time = timer_value x ((8 x 10^-6)/8) */
	distance=(timer_value)/58.8;
	 //distance =(((float32)(timer_value)*17000)/1000000);/*in centimeter*/
	return distance;
}


/*
 * Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by the ultra-sonic sensor.*/
void Ultrasonic_edgeProcessing(void){/**the call back function**/
	timer_value=0;
	if (g_edge_count==0) /*first time being called */
	{
	/*when the fun  is called  by the ISR in ICU
	 * it means rising edge at echo pin is detected and we should start the timer
	 * */
	  ICU_clearTimerValue();/*staring the timer*/
	  ICU_setEdgeDetectionType(FALLING);/*now we wait again for the echo pin to get to LOW = the signal is back to the ULTRASONIC module*/
	  g_edge_count++;
	}
	else if(g_edge_count==1)/*echo pin is low*/
	{
	timer_value=ICU_getInputCaptureValue();/*get the count of the timer captured by the ICU from ICR1 register*/
	  Ultrasonic_readDistance();/*read the timer value in ICU register and calculate distance */
	  ICU_deInit(); /* Disable ICU Driver */
	  Ultrasonic_init();
	  g_edge_count=0;
	}

}
